[tool.ruff]
target-version = "py39"
line-length = 88
src = ["helion"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"
line-ending = "lf"

[tool.ruff.lint]
select = [
    "A", "B", "C4", "COM", "D419", "E", "ERA001", "EXE", "F", "FA", "FLY", "FURB",
    "G", "I", "ISC", "LOG", "NPY", "PERF", "PGH004", "PIE", "PLC0131", "PLC0132",
    "PLC0205", "PLC0208", "PLC2401", "PLC3002", "PLE", "PLR0133", "PLR0206",
    "PLR1722", "PLR1736", "PLW0129", "PLW0131", "PLW0133", "PLW0245", "PLW0406",
    "PLW0711", "PLW1501", "PLW1509", "PLW2101", "PLW3301", "PT", "PYI", "Q", "RET",
    "RSE", "RUF005", "RUF007", "RUF008", "RUF009", "RUF010", "RUF012", "RUF013",
    "RUF015", "RUF016", "RUF017", "RUF018", "RUF019", "RUF020", "RUF022", "RUF024",
    "RUF026", "RUF030", "RUF034", "RUF036", "RUF037", "RUF041", "RUF047", "RUF051",
    "RUF056", "RUF100", "RUF200", "S324", "SIM", "SLOT", "TCH", "TD001", "TD002",
    "TD004", "TRY002", "TRY203", "TRY401", "UP", "W", "YTT",
]
ignore = [
    "COM812", "E501", "ERA001", "PERF203", "SIM102", "SIM108", "SIM115", "C409", "C419"
]
extend-safe-fixes = ["TC", "UP045", "RUF013"]
preview = true
exclude = ["test/data/*"]

[tool.ruff.lint.isort]
extra-standard-library = ["typing_extensions"]
known-local-folder = ["helion"]
known-third-party = ["torch"]
required-imports = ["from __future__ import annotations"]
force-single-line = true  # better merge conflicts
force-sort-within-sections = true
